name: docker-image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jd21/shinyolink
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Setup DOCKERHUB_USERNAME at the repo secret
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Setup DOCKERHUB_TOKEN at the repo secret
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }} 
            jd21/shinyolink:latest